### ISSUE TITLE
Yellow Border Pages for Dat Variant

### ISSUE THREAD

**Issue by cjeller1592** [paul90/wiki-client-dat-variant#3]
I am getting the yellow border around my wiki when I try to edit one of its pages. From what I know about the HTTP wiki, this usually has to do with connection issues or being logged out. I tried reconnecting to the wifi and forking the local changes but that didn't help. 

How does this problem translate over to the Dat variant? Is it the same issues at play or could it be something with Beaker Browser or one of the files that I need to edit?

**Comment by paul90** [comment]
Is this on the computer/user that you created the wiki on?

You should only get the yellow border if you edit a page and are not the wiki owner.

**Comment by cjeller1592** [comment]
I am only using one computer and user for the wiki. It might have got corrupted or something. Here is the codebase: 

beaker://library/dat://f84ddec8e1bcc84c0f75948be442147ba2ccc3e18aaa5002c51691b832513226

Everything looks normal unless there are privileges in the index.html or whatever file that I am missing. Maybe it is an issue with Beaker Browser or Hashbase? Will also check wifi elsewhere to see if that is problem too.

**Comment by paul90** [comment]
Not too sure what is happening.. maybe it has become corrupted, but Beaker is freezing so frequently that it is hard to see what is happening.

Using the dat cli, when I try and download the dat I am only getting the files in the top level directory, not seeing any of the wiki content. If I run `dat log` I am seeing 505 entries, but it also reports that there are 513 changes. So, there is something not quite right. It certainly looks as if hashbase does not have a complete copy of the dat.

If you are the wiki owner is determined by using `getInfo()` and looking that `isOwner`. So, is determined using the dat itself.

**Comment by paul90** [comment]
I'm going to close this issue.

With the release of Beaker v1.0 beta, and the eventual replacement of Hashbase, it should be type of issue is has been fixed.

I will be writing a guide on the steps needed to upgrade from the `dat://` to the `hyper://` version of the wiki soon.
