### ISSUE TITLE
Favicon of hosted frontend, not the wiki's

### ISSUE THREAD

**Issue by almereyda** [paul90/wiki-client-dat-variant#7]
When creating a new wiki, a flag is assigned to it. In Beaker 1.0.0, his will only be shown on the wiki's pages, and not as favicon. The favicon displays the favicon of the hosted frontend instead.

Eventually this is a race condition that occurs when the frontend's favicon becomes available before the actual one in the hyperdrive.

![Bildschirmfoto von 2020-12-06 20-30-29](https://user-images.githubusercontent.com/1645308/101290355-f915a480-3801-11eb-8abf-256209a48e9c.png)

This could also be an upstream issue, Beaker not picking up a newly set favicon dynamically in the tab bar.

**Comment by paul90** [comment]
It looks as if Beaker is caching the favicon it is showing for the tab. It will be refreshed when you restart Beaker.

I will investigate if there is a change that can be made to fix this problem, or if it is something that requires a change in Beaker.

The green favicon is the one used by the empty wiki site that is copied, by the plugin, when creating a new wiki. The hosted `/.ui` has a yellow favicon.

_Probably worth observing that much the same behaviour is seen with the HTTP based wiki._

**Comment by paul90** [comment]
As noted above, this appears to be much the same behaviour as seen with other browsers. I did wonder if there was a Beaker API for setting the favicon, but there isn't.

Going to close this for now.

**Comment by almereyda** [comment]
Thank you for taking the time to investigate this further.
